### ISSUE TITLE
ModuleNotFoundError: No module named 'scripts.models.vmu2'

### ISSUE THREAD

**Issue by kelisiya** [vinthony/deep-blind-watermark-removal#1]
ModuleNotFoundError: No module named 'scripts.models.vmu2',
and how to inference one nature image ?

**Comment by vinthony** [comment]
Thanks for your attention.

I have just fixed this bug.

You can try our [online demo](https://colab.research.google.com/drive/1pYY7byBjM-7aFIWk8HcF9nK_s6pqGwww?usp=sharing) for the inference on one natural image by replacing the data loader with a single natural image.
